### ISSUE TITLE
Add documentation about image types

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin-archive/jellyfin-docs#181]
Jellyfin has a lot of image types:
 - Primary
 - Art
 - Backdrop
 - Banner
 - Box
 - BoxRear
 - Disc
 - Logo
 - Menu
 - Screenshot
 - Thumb

Some of those I know of what they are meant for; primary is the cover, logo is as it says a logo.
However, for most I still have no idea where they are used and what aspect ratio is required. Recommended resolution would also be nice.

My suggestion here is to create a new page in the documentation explaining all those different image types with their use case and optimal aspect ratio / resolution.

**Comment by jamiethomaswhite** [comment]
Need this info asap myself currently, and it would surely make sense and be fully necessary for the documentation.

**Comment by spirillen** [comment]
You can find a bit of guidance at fanart for the sizes https://fanart.tv/tv-fanart/

## LOGO
Image Size 800 x 310px

## Poster
Images sized 1000x1426 pixels (1000x1500)

### Season Poster
Images sized 1000x1426 pixels (1000x1500)

## ClearLOGO Alt. Logo
Image Size 400 x 155px

## ClearART = Thumb
**Ordinary / Small**
Images sized 500x281 pixels
**HD**
mages sized 1000x562 pixels

## Thumbs
Tv-Shows
Images sized 1000x562 pixels

## Background / Backdrop
Images sized 1920x1080 pixels

For 4K monitors you should proportionally upscale but keep aspect ratio

## Banner
Images sized 1000x185 pixels

Please correct me, if I have misunderstood any of the information above, and I modify the reply in conjunction to better information.

**Comment by nielsvanvelzen** [comment]
We've recently discussed image sizes in this discussion too:
https://github.com/jellyfin/jellyfin-meta/issues/12#issuecomment-759373678

**Comment by spirillen** [comment]
Nice link @nielsvanvelzen :+1: an a good table by @MrTimscampi
